### ISSUE TITLE
Exception starting the server

### ISSUE THREAD

**Issue by plun1331** [mcpyproject/McPy#56]
**Describe the bug**
Encountering 2 exceptions when running `startup.py`, EOFError and a TypeError

**To Reproduce**
1. Run startup.py

**Expected behavior**
The server starts

**Screenshots**
```
INFO:root:Getting release list...
INFO:root:McPy found! Running it...
[2021-01-25 11:45:48,759 - INFO - MainThread] Trying to initialize the Blackfire probe
[2021-01-25 11:45:48,760 - INFO - MainThread] Blackfire not installed: passing
[2021-01-25 11:45:48,760 - INFO - MainThread] Starting queues...
[2021-01-25 11:45:48,765 - INFO - MainThread] Started queues!
[2021-01-25 11:45:48,765 - INFO - MainThread] Trying to find number of available cores
[2021-01-25 11:45:48,765 - WARNING - MainThread] Falling back to multiprocessing cpu_count to calc cores. Most likely getaffinity is not supported on your OS
[2021-01-25 11:45:48,765 - INFO - MainThread] Found 2 cores available!
[2021-01-25 11:45:48,766 - INFO - MainThread] Starting worker ID 15824
[2021-01-25 11:45:48,771 - INFO - MainThread] Started worker.
[2021-01-25 11:45:48,882 - INFO - MainThread] Starting networking worker
Traceback (most recent call last):
  File "McPy/main.py", line 238, in <module>
    main()
  File "McPy/main.py", line 221, in main
    networkingProcess.start()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_cffi_backend.FFI' object
[2021-01-25 11:45:49,267 - INFO - MainThread] Trying to initialize the Blackfire probe
[2021-01-25 11:45:49,268 - INFO - MainThread] Blackfire not installed: passing
[2021-01-25 11:45:49,268 - INFO - MainThread] Starting queues...
[2021-01-25 11:45:49,272 - INFO - MainThread] Started queues!
[2021-01-25 11:45:49,273 - INFO - MainThread] Worker ID 15824 has started up.
[2021-01-25 11:45:49,375 - INFO - MainThread] Trying to initialize the Blackfire probe
[2021-01-25 11:45:49,376 - INFO - MainThread] Blackfire not installed: passing
[2021-01-25 11:45:49,376 - INFO - MainThread] Starting queues...
[2021-01-25 11:45:49,380 - INFO - MainThread] Started queues!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

**Host system:**
 - OS: Windows
 - OS version: Version 2004, OS Build 19041.746, 64 Bit
 - Python version 3.8.3, 32 Bit

**Additional context**
If it makes any difference, I installed `Twisted` from https://www.lfd.uci.edu/~gohlke/pythonlibs/#twisted using `Twisted‑20.3.0‑cp38‑cp38‑win32.whl`

**Comment by Geolykt** [comment]
Are you using the 32 bit version of python?

**Comment by plun1331** [comment]
32, yes

**Comment by Geolykt** [comment]
The bug looks similar to #19, although I wouldn't yet consider it a duplicate as It should have been fixed

**Comment by ntoskrnl4** [comment]
yeah that's #19 reincarnated, rip

make sure that you're using the latest version of master branch, also try develop

**Comment by plun1331** [comment]
Cloned the repo about 20 minutes ago, I'll try develop

**Comment by plun1331** [comment]
Problem persists on the develop branch

**Comment by Geolykt** [comment]
Do you still get that blackfire probe stuff twice or is it once again? I'm wondering if it's a hint towards a malfunction within the application

**Comment by plun1331** [comment]
I believe I get it twice

**Comment by Geolykt** [comment]
Could you send the updated log (using the develop branch)?

**Comment by plun1331** [comment]
```
INFO:root:Making sure pip is installed...
Looking in links: c:\Users\USER\AppData\Local\Temp\tmpdbfedzbl
Requirement already up-to-date: setuptools in c:\users\USER\documents\github\mcpy\venv\lib\site-packages (52.0.0)
Requirement already up-to-date: pip in c:\users\USER\documents\github\mcpy\venv\lib\site-packages (21.0)
Installed.
Getting release list...
McPy found! Running it...
[2021-01-25 12:23:17,956 - INFO - MainThread] Trying to initialize the Blackfire probe
[2021-01-25 12:23:17,957 - INFO - MainThread] Blackfire not installed: passing
[2021-01-25 12:23:17,957 - INFO - MainThread] Starting queues...
[2021-01-25 12:23:17,963 - INFO - MainThread] Started queues!
[2021-01-25 12:23:17,963 - INFO - MainThread] Trying to find number of available cores
[2021-01-25 12:23:17,963 - WARNING - MainThread] Falling back to multiprocessing cpu_count to calc cores. Most likely getaffinity is not supported on your OS
[2021-01-25 12:23:17,963 - INFO - MainThread] Found 2 cores available!
[2021-01-25 12:23:17,963 - INFO - MainThread] Starting worker ID 5369
[2021-01-25 12:23:17,968 - INFO - MainThread] Started worker.
[2021-01-25 12:23:17,979 - INFO - MainThread] Starting networking worker
Traceback (most recent call last):
  File "McPy/main.py", line 238, in <module>
    main()
  File "McPy/main.py", line 221, in main
    networkingProcess.start()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\cplun\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_cffi_backend.FFI' object
[2021-01-25 12:23:18,466 - INFO - MainThread] Trying to initialize the Blackfire probe
[2021-01-25 12:23:18,467 - INFO - MainThread] Blackfire not installed: passing
[2021-01-25 12:23:18,467 - INFO - MainThread] Starting queues...
[2021-01-25 12:23:18,471 - INFO - MainThread] Started queues!
[2021-01-25 12:23:18,472 - INFO - MainThread] Worker ID 5369 has started up.
[2021-01-25 12:23:18,483 - INFO - MainThread] Trying to initialize the Blackfire probe
[2021-01-25 12:23:18,483 - INFO - MainThread] Blackfire not installed: passing
[2021-01-25 12:23:18,483 - INFO - MainThread] Starting queues...
[2021-01-25 12:23:18,487 - INFO - MainThread] Started queues!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

**Comment by ntoskrnl4** [comment]
~~Hmm, in the process of debugging I've made an interesting discovery - running the program via `startup.py` incurs different behavior (the error being discussed here) than directly running `main.py` (circular import in classes\\\_\_init\_\_.py: `from . import blocks`).~~ Nevermind, I didn't realize `startup.py` downloads its own McPy into a subfolder. That kinda screws with my Pycharm run configurations...

Anyways, I am able to reproduce this specific problem (W10 1909, 3.8.0 x64). Yikes. My first thought is that maybe it has to do with code being ran multiple times in the worker threads when it's not supposed to.

**Comment by Geolykt** [comment]
Good catch, that main.py appears outdated. @plun1331 try invoking main.py directly (in the same folder startup.py is located at), see if that helps

**Comment by plun1331** [comment]
`ImportError: cannot import name 'Blocks' from partially initialized module 'classes' (most likely due to a circular import) (C:\Users\cplun\Documents\GitHub\McPy\classes\__init__.py)`

**Comment by ntoskrnl4** [comment]
Honestly, all the stuff with `startup.py` is making this way more complicated than it needs to. I'm getting like 3 or 4 all different errors, depending on what branch I'm on, whether I launch using or not using startup.py...

Off-topic to this issue but I think the `startup.py` script should just be scrapped. It's really not hard to click the "Download zip" button in Github if anyone wants to download the program.

**Comment by Geolykt** [comment]
That's what #53 already does

**Comment by Geolykt** [comment]
@plun1331 Are you sure that you are targetting develop? I was able to reproduce this issue in master, but not in develop.
```
[Geolykt@<thing> McPy]$ git checkout master
warning: unable to rmdir 'libs/quarry': Directory not empty
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
[Geolykt@<thing> McPy]$ python3 main.py 
Importing classes, please wait ...
Traceback (most recent call last):
  File "/home/Geolykt/git/McPy/main.py", line 360, in <module>
    import classes
  File "/home/Geolykt/git/McPy/classes/__init__.py", line 2, in <module>
    from . import Blocks
ImportError: cannot import name 'Blocks' from partially initialized module 'classes' (most likely due to a circular import) (/home/Geolykt/git/McPy/classes/__init__.py)
[Geolykt@<thing> McPy]$ git checkout develop
Switched to branch 'develop'
Your branch is up to date with 'origin/develop'.
[Geolykt@<thing> McPy]$ python3 main.py
root | INFO | Blackfire not installed: passing
root | INFO | 4 cores available
root | INFO | Launching server ...
root | INFO | Launching processes ...
root | INFO | Starting worker PROCESS_0
root | INFO | Starting worker PROCESS_1
root | INFO | Starting worker PROCESS_2
root | INFO | Workers started !
root | INFO | Starting ticks
^Croot | INFO | Tick: Got KeyboardInterrupt, interrupting loop
root | INFO | Stopping server ...
root | INFO | Waiting for process to end ...
root | INFO | Process stopped !
root | INFO | Stopping ticks
root | INFO | Server stopped: goodbye!

```

**Comment by plun1331** [comment]
```
C:\Users\user\Documents\GitHub\McPyDev>git branch
* develop

C:\Users\user\Documents\GitHub\McPyDev>python startup.py
INFO:root:Making sure pip is installed...
Looking in links: c:\Users\user\AppData\Local\Temp\tmp63ddshhe
Requirement already up-to-date: setuptools in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (41.2.0)
Requirement already up-to-date: pip in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (21.0)
Installed.
Getting release list...
McPy found! Running it...
[2021-01-25 13:00:12,452 - INFO - MainThread] Trying to initialize the Blackfire probe
[2021-01-25 13:00:12,453 - INFO - MainThread] Blackfire not installed: passing
[2021-01-25 13:00:12,453 - INFO - MainThread] Starting queues...
[2021-01-25 13:00:12,458 - INFO - MainThread] Started queues!
[2021-01-25 13:00:12,458 - INFO - MainThread] Trying to find number of available cores
[2021-01-25 13:00:12,459 - WARNING - MainThread] Falling back to multiprocessing cpu_count to calc cores. Most likely getaffinity is not supported on your OS
[2021-01-25 13:00:12,459 - INFO - MainThread] Found 2 cores available!
[2021-01-25 13:00:12,459 - INFO - MainThread] Starting worker ID 14070
[2021-01-25 13:00:12,464 - INFO - MainThread] Started worker.
[2021-01-25 13:00:12,496 - INFO - MainThread] Starting networking worker
Traceback (most recent call last):
  File "McPy/main.py", line 238, in <module>
    main()
  File "McPy/main.py", line 221, in main
    networkingProcess.start()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_cffi_backend.FFI' object
[2021-01-25 13:00:12,995 - INFO - MainThread] Trying to initialize the Blackfire probe
[2021-01-25 13:00:12,996 - INFO - MainThread] Blackfire not installed: passing
[2021-01-25 13:00:12,996 - INFO - MainThread] Starting queues...
[2021-01-25 13:00:13,001 - INFO - MainThread] Started queues!
[2021-01-25 13:00:13,001 - INFO - MainThread] Worker ID 14070 has started up.
[2021-01-25 13:00:13,028 - INFO - MainThread] Trying to initialize the Blackfire probe
[2021-01-25 13:00:13,029 - INFO - MainThread] Blackfire not installed: passing
[2021-01-25 13:00:13,029 - INFO - MainThread] Starting queues...
[2021-01-25 13:00:13,033 - INFO - MainThread] Started queues!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by ntoskrnl4** [comment]
@Geolykt the version of the program that `startup.py` runs is different than the version in the repo. You have to run `McPy/main.py` to get that one, which has the issue in this thread. 

...I'll work on merging #53... lol

**Comment by plun1331** [comment]
Well, running main.py on dev seems to work fine
